// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ACTech.Models
{
    [Table("Course")]
    public partial class Course
    {
        public Course()
        {
            Grades = new HashSet<Grade>();
        }

        [Key]
        public int Id { get; set; }
        [Column("Course")]
        [StringLength(10)]
        public string Course1 { get; set; }
        [Column("Course Description")]
        [StringLength(33)]
        public string CourseDescription { get; set; }

        [InverseProperty(nameof(Grade.Course))]
        public virtual ICollection<Grade> Grades { get; set; }
    }
}