// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ACTech.Models
{
    [Table("Education")]
    public partial class Education
    {
        [Key]
        public int Id { get; set; }
        [Column("Education")]
        [StringLength(50)]
        public string Education1 { get; set; }
    }
}