// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ACTech.Models
{
    [Table("Employment")]
    public partial class Employment
    {
        [Key]
        public int Id { get; set; }
        [Column("Employment")]
        [StringLength(14)]
        public string Employment1 { get; set; }
    }
}