// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ACTech.Models
{
    [Table("Student Company")]
    public partial class StudentCompany
    {
        [Key]
        public int Id { get; set; }
        [Column("STUDENT_ID")]
        [StringLength(11)]
        public string StudentId { get; set; }
        [Column("Work Status")]
        public int? WorkStatus { get; set; }
        [StringLength(50)]
        public string Company { get; set; }
        [Column("Work Phone")]
        [StringLength(14)]
        public string WorkPhone { get; set; }
        [Column("Work Address")]
        [StringLength(70)]
        public string WorkAddress { get; set; }

        [ForeignKey(nameof(StudentId))]
        [InverseProperty("StudentCompanies")]
        public virtual Student Student { get; set; }
    }
}