// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ACTech.Models
{
    [Table("Student Address")]
    public partial class StudentAddress
    {
        [Key]
        public int Id { get; set; }
        [Required]
        [Column("STUDENT_ID")]
        [StringLength(11)]
        public string StudentId { get; set; }
        [Column("ADDRESS")]
        [StringLength(30)]
        public string Address { get; set; }
        [Column("ADDRESS2")]
        [StringLength(30)]
        public string Address2 { get; set; }
        [Column("CITY")]
        [StringLength(30)]
        public string City { get; set; }
        [Column("STATE")]
        [StringLength(2)]
        public string State { get; set; }
        [Column("ZIP")]
        [StringLength(10)]
        public string Zip { get; set; }

        [ForeignKey(nameof(StudentId))]
        [InverseProperty("StudentAddresses")]
        public virtual Student Student { get; set; }
    }
}